version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/App.js
      - /App.js/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

    command: npm start

