name: Lint Code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  lint:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npx eslint .
